### ISSUE TITLE
snw.jkook.message.Message类getQuote()方法 连续获取时返回为空

### ISSUE THREAD

**Issue by cnluminous** [SNWCreations/JKook#20]
### 错误日志

```java
[12:37:59] [Event Executor/ERROR]: java.lang.NullPointerException: Cannot invoke "snw.jkook.message.Message.getComponent()" because the return value of "snw.jkook.message.Message.getQuote()" is null
[12:37:59] [Event Executor/ERROR]: 	at com.cnluminous.ChatListener.getHistory(ChatListener.java:43)
[12:37:59] [Event Executor/ERROR]: 	at com.cnluminous.ChatListener.onChannelChat(ChatListener.java:27)
[12:37:59] [Event Executor/ERROR]: 	at snw.kookbc.impl.event.EventExecutorFactoryImpl.lambda$create$0(EventExecutorFactoryImpl.java:48)
[12:37:59] [Event Executor/ERROR]: 	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148)
[12:37:59] [Event Executor/ERROR]: 	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107)
[12:37:59] [Event Executor/ERROR]: 	at snw.kookbc.impl.event.EventManagerImpl.callEvent(EventManagerImpl.java:53)
[12:37:59] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:155)
[12:37:59] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:108)
[12:37:59] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:69)
[12:37:59] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:37:59] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:37:59] [Event Executor/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
``` 

### 复现代码
```java
public void getHistory(List<History> histories, snw.jkook.message.Message message){
        snw.jkook.message.Message quote;
        if (message.getQuote()!=null){//has quote
            quote = message.getQuote();

//            quote = BotPlugin.getInstance().getCore().getHttpAPI().getTextChannelMessage(message.getQuote().getId()); //另一种可成功获取消息方法
            if (quote.getSender().getId().equals(BotPlugin.getInstance().getCore().getUser().getId())){//is bot
                if (quote.getQuote()==null){
                    return;
                }
                History history = History.builder().build();
                String qs = quote.getQuote().getComponent().toString().replaceAll(metRegex,"");//question string
                history.setUser(qs);
                String as = quote.getComponent().toString().replaceAll(metRegex,"");//answer string
                if (quote.getComponent() instanceof CardComponent){
                    BaseModule module = ((CardComponent) quote.getComponent()).getModules().get(((CardComponent) quote.getComponent()).moduleCount()-1);
                    if (module instanceof SectionModule){
                        if (((SectionModule) module).getText() instanceof MarkdownElement){
                            as = ((MarkdownElement) ((SectionModule) module).getText()).getContent();
                        }
                    }
                }
                history.setBot(as);
                histories.add(history);
//                System.out.println("qs = " + qs);
//                System.out.println("as = " + as);
            }
            getHistory(histories,quote);
        }
``` 
### 预期效果
根据回复消息内容，连续获取上一条内容直至为空

### 实际效果
仅能获取到当前回复的消息，无法连续获取

![image](https://github.com/SNWCreations/JKook/assets/47070284/5717396f-949d-40af-99b0-274655ac83fb)

**Comment by xiaoACE6716** [comment]
复现成功！
(这里是我的猜测!) 可能夏夜构造 `Message.getQuote()` 返回的 Message 对象的时候(后面称为 quote )，没有放入 quote 的 上一级消息的id (或许事件没提供所以就没有放入) ，所以获取到的是 null 或者造成空指针异常。

我这有个解决办法就是，`Message.getQuote()` 的时候取 quote 的 消息ID，然后用HttpAPI里面的 `getXXMessage()` 方法来获得 
 quote 对象，这样就能对 quote 使用 getQuote 方法了。

`String quoteID = event.getMessage().getQuote().getId();`
`quote = Main.getInstance().getCore().getHttpAPI().getTextChannelMessage(quoteID);`

**Comment by SNWCreations** [comment]
你可以试试先自行修复。
我暂时抽不开身。

**Comment by SNWCreations** [comment]
最新的 KookBC dev分支代码尝试修复了这个问题。请测试。
此问题应该属于实现问题，其实应该投递到 KookBC 仓库。

这两个月真的实在是太忙了....现在才修，我深感抱歉。
